// <auto-generated />
using System;
using Init.Io.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Init.Io.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260928204809_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("BaseEntitySequence");

            modelBuilder.Entity("Init.Io.API.Models.Entity.BaseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"BaseEntitySequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.ContentBlockEntity", b =>
                {
                    b.HasBaseType("Init.Io.API.Models.Entity.BaseEntity");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("OrdinalPosition")
                        .HasColumnType("integer");

                    b.Property<long>("SectionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasIndex("SectionId");

                    b.ToTable("content_blocks", (string)null);
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.DepartmentEntity", b =>
                {
                    b.HasBaseType("Init.Io.API.Models.Entity.BaseEntity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.HasIndex("OrganizationId");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.OnboardingFlowEntity", b =>
                {
                    b.HasBaseType("Init.Io.API.Models.Entity.BaseEntity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasIndex("TeamId");

                    b.ToTable("onboarding_flows", (string)null);
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.OrganizationEntity", b =>
                {
                    b.HasBaseType("Init.Io.API.Models.Entity.BaseEntity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.SectionEntity", b =>
                {
                    b.HasBaseType("Init.Io.API.Models.Entity.BaseEntity");

                    b.Property<long>("OnboardingFlowId")
                        .HasColumnType("bigint");

                    b.Property<int>("OrdinalPosition")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasIndex("OnboardingFlowId");

                    b.ToTable("sections", (string)null);
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.TeamEntity", b =>
                {
                    b.HasBaseType("Init.Io.API.Models.Entity.BaseEntity");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.HasIndex("DepartmentId", "Name")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.TeamUserEntity", b =>
                {
                    b.HasBaseType("Init.Io.API.Models.Entity.BaseEntity");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique();

                    b.ToTable("team_users", (string)null);
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.UserEntity", b =>
                {
                    b.HasBaseType("Init.Io.API.Models.Entity.BaseEntity");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfilePhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.BaseEntity", b =>
                {
                    b.HasOne("Init.Io.API.Models.Entity.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Init.Io.API.Models.Entity.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.ContentBlockEntity", b =>
                {
                    b.HasOne("Init.Io.API.Models.Entity.SectionEntity", null)
                        .WithMany("ContentBlocks")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.DepartmentEntity", b =>
                {
                    b.HasOne("Init.Io.API.Models.Entity.OrganizationEntity", null)
                        .WithMany("Departments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.OnboardingFlowEntity", b =>
                {
                    b.HasOne("Init.Io.API.Models.Entity.TeamEntity", "Team")
                        .WithMany("OnboardingFlows")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.SectionEntity", b =>
                {
                    b.HasOne("Init.Io.API.Models.Entity.OnboardingFlowEntity", null)
                        .WithMany("Sections")
                        .HasForeignKey("OnboardingFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.TeamEntity", b =>
                {
                    b.HasOne("Init.Io.API.Models.Entity.DepartmentEntity", "Department")
                        .WithMany("Teams")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Init.Io.API.Models.Entity.OrganizationEntity", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.TeamUserEntity", b =>
                {
                    b.HasOne("Init.Io.API.Models.Entity.TeamEntity", "Team")
                        .WithMany("TeamUsers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Init.Io.API.Models.Entity.UserEntity", "User")
                        .WithMany("TeamUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.UserEntity", b =>
                {
                    b.HasOne("Init.Io.API.Models.Entity.DepartmentEntity", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Init.Io.API.Models.Entity.OrganizationEntity", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.DepartmentEntity", b =>
                {
                    b.Navigation("Teams");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.OnboardingFlowEntity", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.OrganizationEntity", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Teams");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.SectionEntity", b =>
                {
                    b.Navigation("ContentBlocks");
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.TeamEntity", b =>
                {
                    b.Navigation("OnboardingFlows");

                    b.Navigation("TeamUsers");
                });

            modelBuilder.Entity("Init.Io.API.Models.Entity.UserEntity", b =>
                {
                    b.Navigation("TeamUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
